[WIP] Jr/mongo dump
hethune/simple-backup pull request #1
Opened 2018-07-12 10:21 UTC by jerryan9999

1.  Mongo dump periodic job 
2. S3 upload function
3. config

2018-07-12 12:04 UTC, jerryan9999 commented
@hethune

2018-07-12 12:05 UTC, jerryan9999 commented
4. bash script

2018-07-20 03:56 UTC, hethune requested changes

2018-07-20 03:56 UTC, hethune commented on config.py
> +    self.is_s3 = config["is_s3"]
config.get("is_s3")

2018-07-20 03:56 UTC, hethune commented on jobs/__init__.py
> +  def construct_filename(prefix, tags, suffix, base_folder,dt=None):
`dt` or `ds`?

2018-07-20 03:56 UTC, hethune commented on one-off/mongobatchbackup.sh
> +MONGODB_HOST='127.0.0.1:27017'
make these command line args

2018-07-20 03:56 UTC, hethune commented on one-off/mongobatchbackup.sh
> +MONGODB_HOST='127.0.0.1:27017'
用python script更好 因为可以直接读config.yml
mongo_user这些都不用再写了

2018-07-20 06:13 UTC, jerryan9999 commented on jobs/__init__.py
> +  def construct_filename(prefix, tags, suffix, base_folder,dt=None):
是dt,下一行的参变量写错了

2018-07-20 06:58 UTC, hethune approved these changes
LGTM

2018-07-20 07:48 UTC, merged